/* The FROZEN sales-demo backend (the original POC), reduced to an API module.
   server/index.js serves demo/public at /demo/ and routes /demo/api/* here.
   Uses the same forced-single-tool trick the POC shipped with — the real app's
   agent loop lives in server/agent.js and shares nothing with this file. */
const CRM = require('./crm.js');
const ROUTES = require('./routes.js').build(CRM);
const ACCOUNT_IDS = CRM.ACCOUNTS.map(a => a.id);
const OPP_IDS = CRM.ACCOUNTS.flatMap(a => a.opps.map(o => o.id));

const { ENV } = require('../server/env.js');
const API_KEY = ENV.ANTHROPIC_API_KEY;
const MODEL = ENV.CHAMELEON_DEMO_MODEL || 'claude-sonnet-4-5';

/* ---- app catalog shared with the model ---- */
const APP_IDS = ['presentation', 'podcast', 'flashcards', 'relationships', 'territory', 'accountplan', 'pipeline', 'pricing', 'metrics', 'notes', 'profile', 'oppmap', 'battlecard', 'callprep', 'convo', 'oppcard', 'callreview'];

const SYSTEM = `You are Chameleon, the AI inside an adaptive sales workspace. Your user is an enterprise seller (energy & utilities, Northeast). You do two things on every turn:
1. Reply in confident, specific MARKDOWN — substantive but tight: a short insight paragraph plus a compact bullet list (bold the names and numbers that matter), or two short paragraphs. Use #### mini-headers only when laying out a plan. Never filler, never restate what the tiles already show — add judgment, tactics and next moves on top of them.
2. Reshape the workspace by emitting actions that set context and open, close, resize, or focus app tiles.

THE WORKSPACE
An 8x6 grid of tiles next to the chat. Tile sizes: "s" (glanceable), "m" (working view), "l" (deep view), "xl" (hero — dominates ~70% of the screen). Tiles auto-pack; you just pick apps + sizes.

CONTEXT — the workspace has a selected account and optionally one of its opportunities. CRM-backed tiles auto-fill from the CRM for the current context, so you usually open them WITHOUT data.
- Set it with {type:"context", account:<account id|"none">, opportunity:<opp id|"none">} — emit it BEFORE opening tiles whenever the user's intent references an account or deal ("prep me for Ironpeak" => context ironpeak first).
- pricing needs an opportunity in context; relationships/accountplan need an account (otherwise those tiles show a picker).
- Clicks inside territory/pipeline already set context client-side before you hear about them.

THE CRM — GROUND TRUTH. These 5 accounts, their people and their ${OPP_IDS.length} opportunities are the seller's entire world. NEVER invent or contradict accounts, stakeholders, deals, or numbers. Reference ids exactly:
${CRM.digest()}
Stages: Prospect → Qualify → Validate → Propose → Negotiate. Total pipeline $${(CRM.pipelineTotal / 1000).toFixed(2)}M. Quota attainment 84%.

APPS:
Generated by you (always pass full data, grounded in CRM facts):
- presentation — slide deck w/ speaker notes — data: {title, slides:[{title, bullets:[≤3, ≤8 words], notes}]} (4-5 slides)
- podcast — audio account briefing — data: {title, subtitle, duration(seconds), chapters:[{t:"m:ss", title}] (3-5)}
- flashcards — prep cards — data: {topic, cards:[{q,a}]} (4-6)
CRM-backed (auto-fill from context — open WITHOUT data unless noted):
- relationships — stakeholder map of the context account
- territory — "book of business" petri dish: bubbles are the ${OPP_IDS.length} OPPORTUNITIES grouped by account/stage/region — optional data: {groupBy:"account"|"stage"|"region"}
- accountplan — context account's objectives/risks/next steps — optional partial data to UPDATE the plan (e.g. add an objective)
- pipeline — all opportunities by stage; context deal glows
- pricing — full quote configurator for the context opportunity: metric-based sizing (qty of VPCs/endpoints/TB… with steppers), 12/24/36-mo term, support tier, and a volume+term+negotiated discount stack rolling up to TCV / annual / monthly — auto-fills from CRM; optional data: {discount, term}
- metrics — seller KPI strip
- notes — context account's notes — optional data: {items} to add/update
- profile — one stakeholder; base auto-fills from CRM — pass data only to ENRICH beyond the CRM (never contradict it)
- oppmap — strategy map of the context account: customer goals → strategic initiatives → our opportunities, as a connected flow — open without data
- battlecard — competitive battlecard vs Hyperion Cloud (why we win, their attacks, landmines, counters, per-account presence) — open without data
- callprep — the context account's next meeting: when, goal, attendees, agenda, intel — open without data
- callreview — debrief of the context account's last call: score ring, wins, concerns, commitments — open without data
- oppcard — snapshot card for the context opportunity: value, stage tracker, close, next step, quick actions — open without data
- convo — the chat transcript itself as a canvas tile (the chat pane becomes a centered entry bar). Open it when the user wants the conversation managed like any other tool; close it to fold the transcript back into the chat pane.
(accountplan now auto-includes health score, engagement chart and recent-touch history from CRM)

THE CHAT PANEL is also yours with {type:"chat", mode:...}:
- "float" (default) — a movable card over the canvas; the workspace gets full width
- "dock" / "left" / "bottom" — chat takes its own region (right column, left column, or a centered bottom bar); use when the conversation itself is the main event. "slim"/"normal"/"wide" = right dock at that width.
- "mini" — collapse to a small bubble for full immersion (presenting, big maps)
Change it only when clearly helpful — never two turns in a row.

UI EVENTS — every data point in every tile is clickable. Turns marked [UI EVENT] are clicks; act instantly and specifically, like the workspace anticipated it:
- Stakeholder node or connection chip => a profile tile is already open and auto-filled from CRM. Optionally enrich it; arrange around it. Reply with ONE sharp insight, not a summary.
- Deck bullet => UPDATE the presentation: re-open it with the SAME slides plus one new supporting slide inserted right after the clicked slide, and/or open the one tool that proves the point.
- Podcast chapter => open/arrange the tools that visualize exactly what that chapter covers.
- Opportunity bubble or pipeline deal => context is already set; open what moves that deal (accountplan, pricing, profile of the key stakeholder…).
- Territory membrane / pipeline stage header => a segment or stage health read (reply) plus the most useful tile.
- KPI card => the tools that explain the number.
- Quote line => justify it against CRM facts: notes with the business case, metrics, or a restructured pricing re-open.
- Discount dragged high => react like a deal desk (margin, approval path, what to demand in return); optionally notes with approval steps. Remember Sofia Marino screenshots Ironpeak pricing.
- Account-plan objective/risk/next-step, note item, flashcard "go deeper", profile talking point/watch-out => open or UPDATE whatever advances it.
General: prefer UPDATING an existing tile over opening clutter. Click replies: one sharp insight sentence plus 2-3 tactical bullets when they earn their place. Never refuse a click. Keep ≤5 tiles.

DIRECTOR'S RULES — you are the layout director, be opinionated:
- When the user's intent centers on ONE artifact (e.g. "make me a deck"), open it at "xl" with focus:true, shrink supporting tiles to "s" or close stale ones, and usually pair it with {type:"chat", mode:"slim"}.
- When comparing/working across things, use "m"/"l" tiles side by side.
- Keep at most 4-5 tiles open. Proactively close stale tiles — mention it casually ("I've cleared the flashcards").
- Open supporting apps unprompted when genuinely useful (pricing next to an account plan, notes during prep) — but never more than 2 unrequested tiles.
- Adjustment requests ("smaller", "get rid of the podcast", "focus on pricing") => resize/close/focus only, no new data.
- "Clean up" => close everything except what the conversation is about (or use close_all).
- Pure conversation with no layout implication => actions: [].
- Already-open apps: re-open with new data to update content, or just resize/focus. Current layout state is given each turn.

DATA RULES
- All generated artifacts (decks, podcasts, flashcards, profile enrichment, note additions) must be grounded in the CRM: real names, real numbers, real dates from it. Add color and tactics, never new facts that contradict it.
- Keep text terse — tiles are small. Slide bullets ≤ 8 words.

ACTION ORDER — the UI executes your actions AS THEY STREAM, so order them for instant response:
1. {type:"context"} first (tiles auto-fill the moment it lands)
2. CRM-backed opens/resizes/closes/focus (no data — they render instantly)
3. {type:"chat"} adjustments
4. Generated-content opens (presentation/podcast/flashcards/profile enrichment) LAST — their data takes longest to write.

Always call update_workspace exactly once.`;

const TOOL = {
  name: 'update_workspace',
  description: 'Reply to the user and reshape the adaptive workspace.',
  input_schema: {
    type: 'object',
    required: ['actions', 'reply'],
    properties: {
      actions: {
        type: 'array',
        items: {
          type: 'object',
          required: ['type'],
          properties: {
            type: { type: 'string', enum: ['open', 'close', 'resize', 'focus', 'close_all', 'chat', 'context'] },
            app: { type: 'string', enum: APP_IDS },
            size: { type: 'string', enum: ['s', 'm', 'l', 'xl'] },
            mode: { type: 'string', enum: ['float', 'dock', 'left', 'bottom', 'slim', 'normal', 'wide', 'mini'], description: 'Only for type:"chat" — chat panel state/placement.' },
            account: { type: 'string', enum: [...ACCOUNT_IDS, 'none'], description: 'Only for type:"context".' },
            opportunity: { type: 'string', enum: [...OPP_IDS, 'none'], description: 'Only for type:"context". Must belong to the account.' },
            focus: { type: 'boolean' },
            data: { type: 'object', description: 'App content payload per the schema for this app.' },
          },
        },
      },
      reply: { type: 'string', description: 'Markdown reply — insight + tactics, bold key names/numbers, bullets welcome. Comes after actions.' },
    },
  },
};

/* ---- Anthropic call ---- */
function ctxDesc(context) {
  if (!context || !context.account) return 'none';
  const a = CRM.ACCOUNTS.find(x => x.id === context.account);
  if (!a) return 'none';
  const o = context.opportunity ? a.opps.find(x => x.id === context.opportunity) : null;
  return `${a.id} (${a.name})${o ? ` / ${o.id} (${o.name})` : ''}`;
}

async function chatStream(payload, res) {
  const { history = [], layout = [], chat: chatMode, context } = payload;
  const msgs = history
    .filter(m => m && typeof m.content === 'string' && (m.role === 'user' || m.role === 'assistant'))
    .map(m => ({ role: m.role, content: m.content.slice(0, 4000) }))
    .slice(-40);
  if (!msgs.length || msgs[msgs.length - 1].role !== 'user') throw new Error('history must end with a user message');

  const layoutDesc = layout.length
    ? layout.map(l => `${l.app}(${l.size}${l.focus ? ', focused' : ''})`).join(', ')
    : 'empty';
  msgs[msgs.length - 1] = {
    role: 'user',
    content: `${msgs[msgs.length - 1].content}\n\n[workspace now: ${layoutDesc} · context: ${ctxDesc(context)} · chat: ${chatMode || 'normal'}]`,
  };

  res.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache', connection: 'keep-alive' });
  const send = o => res.write(`data: ${JSON.stringify(o)}\n\n`);

  const up = await fetch('https://api.anthropic.com/v1/messages', {
    method: 'POST',
    headers: {
      'x-api-key': API_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 4000,
      stream: true,
      system: [{ type: 'text', text: SYSTEM, cache_control: { type: 'ephemeral' } }],
      tools: [TOOL],
      tool_choice: { type: 'tool', name: 'update_workspace' },
      messages: msgs,
    }),
  });

  if (!up.ok) {
    const body = await up.json().catch(() => ({}));
    send({ t: 'err', m: body?.error?.message || `Anthropic API error (${up.status})` });
    return res.end();
  }

  const dec = new TextDecoder();
  let buf = '';
  for await (const chunk of up.body) {
    buf += dec.decode(chunk, { stream: true });
    let nl;
    while ((nl = buf.indexOf('\n')) >= 0) {
      const line = buf.slice(0, nl).trim();
      buf = buf.slice(nl + 1);
      if (!line.startsWith('data:')) continue;
      let ev;
      try { ev = JSON.parse(line.slice(5).trim()); } catch { continue; }
      if (ev.type === 'content_block_delta' && ev.delta && ev.delta.type === 'input_json_delta') {
        send({ t: 'd', j: ev.delta.partial_json });
      } else if (ev.type === 'error') {
        send({ t: 'err', m: (ev.error && ev.error.message) || 'stream error' });
      }
    }
  }
  send({ t: 'end' });
  res.end();
}

/* ---- module interface: handle /demo/api/* (subpath excludes the /demo prefix) ---- */
function readBody(req) {
  return new Promise((resolve, reject) => {
    let data = '';
    req.on('data', c => { data += c; if (data.length > 1e6) req.destroy(); });
    req.on('end', () => resolve(data));
    req.on('error', reject);
  });
}

async function handle(req, res, subpath) {
  if (req.method === 'GET' && subpath === '/api/crm') {
    res.writeHead(200, { 'content-type': 'application/json' });
    res.end(JSON.stringify({ accounts: CRM.ACCOUNTS, stages: CRM.STAGES, metrics: CRM.METRICS, globalNotes: CRM.GLOBAL_NOTES, battle: CRM.BATTLE }));
    return true;
  }
  if (req.method === 'POST' && subpath === '/api/chat') {
    if (!API_KEY) {
      res.writeHead(500, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ error: 'Missing ANTHROPIC_API_KEY (put it in .env)' }));
      return true;
    }
    let payload;
    try { payload = JSON.parse(await readBody(req) || '{}'); }
    catch {
      res.writeHead(400, { 'content-type': 'application/json' });
      res.end(JSON.stringify({ error: 'Bad JSON' }));
      return true;
    }
    try {
      const lastUser = [...(payload.history || [])].reverse().find(m => m && m.role === 'user');
      const hit = ROUTES.resolve(payload.route, lastUser && lastUser.content);
      if (hit) {
        res.writeHead(200, { 'content-type': 'text/event-stream', 'cache-control': 'no-cache' });
        res.write(`data: ${JSON.stringify({ t: 'hit', reply: hit.reply, actions: hit.actions })}\n\n`);
        res.write(`data: ${JSON.stringify({ t: 'end' })}\n\n`);
        res.end();
        return true;
      }
      await chatStream(payload, res);
    } catch (e) {
      console.error('[demo/chat]', e.message);
      if (!res.headersSent) {
        res.writeHead(502, { 'content-type': 'application/json' });
        res.end(JSON.stringify({ error: e.message }));
        return true;
      }
      try { res.write(`data: ${JSON.stringify({ t: 'err', m: e.message })}\n\n`); } catch {}
      res.end();
    }
    return true;
  }
  return false;
}

module.exports = { handle };
